# Start XDG autostart .desktop files using dex. See also
# https://wiki.archlinux.org/index.php/XDG_Autostart
exec --no-startup-id dex --autostart --environment i3

# Set wallpaper
exec --no-startup-id nitrogen --restore

# Start Picom
exec --no-startup-id picom

# Enable numlock key
exec --no-startup-id numlockx

# Start polkit
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Start Polybar
exec_always --no-startup-id ~/.config/polybar/launch.sh
