# Set i3 colors
set $bar-bg-color #32302f
set $bar-separator-color #665c54
set $bg-color #8ec07c
set $inactive-bg-color #32302f
set $text-color #282828
set $inactive-text-color #ebdbb2
set $urgent-bg-color #fb4934
set $indicator-color #32302f

# Window colors
client.focused $bg-color $bg-color $text-color $indicator-color
client.unfocused $inactive-bg-color $inactive-bg-color $inactive-text-color $indicator-color
client.focused_inactive $inactive-bg-color $inactive-bg-color $inactive-text-color $indicator-color
client.urgent $urgent-bg-color $urgent-bg-color $text-color $indicator-color
