# Set i3 colors (Gruvbox dark)
set $bar-accent-color #32302f
set $bar-separator-color #665c54
set $accent-color #61afef
set $inactive-accent-color #32302f
set $text-color #282828
set $inactive-text-color #ebdbb2
set $urgent-accent-color #e06c75
# set $indicator-color #32302f

# Window colors
client.focused $accent-color $accent-color $text-color $accent-color
client.unfocused $inactive-accent-color $inactive-accent-color $inactive-text-color $accent-color
client.focused_inactive $inactive-accent-color $inactive-accent-color $inactive-text-color $accent-color
client.urgent $urgent-accent-color $urgent-accent-color $text-color $accent-color
