# Gaps
gaps inner 5px
gaps outer 5px

# Smart gaps hide gaps when 1 window is open
# smart_gaps on

# Borders
# Smart borders hide window borders (excluding window title) when 1 window is open
# smart_borders on
