# power menu
set $Locker betterlockscreen -l

set $mode_system System (l) lock, (e) exit, (s) suspend, (r) reboot, (Shift+s) shutdown

mode "$mode_system" {
        bindsym l exec --no-startup-id $Locker, mode "default"
        bindsym e exec --no-startup-id i3-msg exit, mode "default"
        bindsym s exec --no-startup-id systemctl suspend, mode "default"
        bindsym r exec --no-startup-id systemctl reboot, mode "default"
        bindsym Shift+s exec --no-startup-id systemctl poweroff -i, mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+Shift+p mode "$mode_system"

# Power saving menu
set $mode_powersave Power mode (s) power-saver (b) balanced (p) performance

mode "$mode_powersave" {
        bindsym s exec --no-startup-id powerprofilesctl set power-saver, mode "default"
        bindsym b exec --no-startup-id powerprofilesctl set balanced, mode "default"
        bindsym p exec --no-startup-id powerprofilesctl set performance, mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+p mode "$mode_powersave"

# Wifi menu
set $mode_networking Networking (w) wifi on (Shift+w) wifi off (r) rescan networks (n) nmtui

mode "$mode_networking" {
    bindsym w exec --no-startup-id nmcli radio wifi on, mode "default"
    bindsym Shift+w exec --no-startup-id nmcli radio wifi off, mode "default"
    bindsym r exec --no-startup-id nmcli dev wifi rescan, mode "default"
    bindsym n exec --no-startup-id alacritty -e nmtui, mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+n mode "$mode_networking"

# Marks menu
set $mode_marks Marks (a) add (g) goto (d) delete

mode "$mode_marks" {
    bindsym a exec --no-startup-id i3-input -F 'mark %s' -l 1 -P 'Mark: ', mode "default"
    bindsym g exec --no-startup-id i3-input -F '[con_mark="%s"] focus' -l 1 -P 'Goto: ', mode "default"
    bindsym d exec --no-startup-id i3-input -F 'unmark %s' -l 1 -P 'Mark: ', mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+m mode "$mode_marks"

mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

set $mode_scratchpad Scratchpad (s) show (h) hide (l) list

mode "$mode_scratchpad" {
    bindsym s scratchpad show, mode "default"
    bindsym h move scratchpad, mode "default"
    bindsym l exec --no-startup-id rofi -show window, mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+s mode "$mode_scratchpad"
