# Drag windows with titlebar
tiling_drag modifier titlebar

# Make Picture-in-Picture window follow workspace change
for_window [title="Picture-in-Picture"] sticky enable

# Make workspace 5 floating
for_window [ workspace="5" ] floating enable

# Default border size
default_border pixel 2px
